### ISSUE TITLE
Working Demo

### ISSUE THREAD

**Issue by vAStrohhecker** [3qnexx/nexxPLAY-android#38]
Hi, can you provide a working demo for your latest release?
The one in this repo uses 3.+, and when trying to run it i get compilation errors like "error: resource android:attr/dialogCornerRadius not found."

I have tried to use the player in a blank project, but there i get "java.lang.ClassCastException: Bootstrap method returned null" when  calling "player.setViewRoot(root);"

**Comment by mfentross** [comment]
Hi @vAStrohhecker, we are currently updating the demo application. You can expect a new version by Monday.

**Comment by mfentross** [comment]
We updated the demo project to recent versions. The project uses AndroidX now.

**Comment by vAStrohhecker** [comment]
Nice, checking it out now.

**Comment by vAStrohhecker** [comment]
Works like a charm, thanks.
