### ISSUE TITLE
Video not starting

### ISSUE THREAD

**Issue by vAStrohhecker** [3qnexx/nexxPLAY-android#39]
I have implemented your player in a Flutter plugin, but the videos are not playing. I have compared it to your sample and everything is the same. The logs are also the same up to a specific point.

Here are my log outputs:

D/tv.nexx.android.player.logic.PlayerLogicStateMachine(25338): startMediaOrGetReady()
D/de.vonaffenfels.flutternexxtv.NexxPlayerView(25338): Player event in App: PLAYERREADY, null

I/NEXX    (25338): release
D/NEXX    (25338): playing media http://nq-p01.akamaized.net/c64f932b-3230-4874-a0cf-db1f7ef0e353/1520563_src.ism/Manifest(format=mpd-time-cmaf)

I/NEXX    (25338): prepare http://nq-p01.akamaized.net/c64f932b-3230-4874-a0cf-db1f7ef0e353/1520563_src.ism/Manifest(format=mpd-time-cmaf), start position 0

I/NEXX    (25338): prepare has no effect
D/NEXX    (25338): Sequencer event startMedia in state MediaState, transitioning to 2

D/showAgeRestriction(25338): setting header: Warnung.
D/showAgeRestriction(25338): setting body: Dieses Video könnte jugendgefährdende Inhalte enthalten.

I don't know why i am getting the "**prepare has no effect**" message. Customer oder Media ID are those from your sample. As you can see, i even get the age restriction message.
Comparing it to the sample, after "prepare" i should get "player state PREPARING" and the corresponding player event should fire, but not in my case.

Any ideas what i'm doing wrong?

compile SDK is **28** as well as the targetSdkVersion. minSdkVersion is **23**. Plugin is written in Kotlin, using your "tv.nexx:nexxplay-android:4.+" dependency.

**Comment by neko-fire** [comment]
Thanks for the logs, please provide sample code of how you try to play a video so that we can reproduce the issue on our end.

**Comment by vAStrohhecker** [comment]
Here is my main code snippet:
`
package de.vonaffenfels.flutternexxtv

import android.app.Activity
import android.content.Context
import android.util.Log
import android.view.ViewGroup
import android.widget.FrameLayout
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.platform.PlatformView
import tv.nexx.android.player.*
import tv.nexx.android.player.control.LoaderSkin
import tv.nexx.android.player.player.Player


class NexxPlayerView(private val context: Context, id: Int, messenger: BinaryMessenger, activity: Activity) : PlatformView, ActivityAware,
        MethodChannel.MethodCallHandler, NexxPlayerNotification.Listener {


    private val TAG: String = NexxPlayerView::class.java.name

    private val channel = MethodChannel(messenger, "de.vonaffenfels.nexxtv/player/$id")

    private var container: ViewGroup?
    private var nexxPlayer: NexxPlayerAndroid

    init {
        Log.d(TAG, "init NexxPlayerView id: $id")
        channel.setMethodCallHandler(this)

        container = FrameLayout(context).apply {
            layoutParams = FrameLayout.LayoutParams(
                    FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.WRAP_CONTENT
            )
            descendantFocusability = ViewGroup.FOCUS_BLOCK_DESCENDANTS
        }

        nexxPlayer = NexxFactory.createNexxPlayer(context)
        nexxPlayer.setViewRoot(container)
        nexxPlayer.setWindow(activity.window);
    }


    override fun getView() = container

    override fun dispose() {
        container?.removeAllViews()
        channel.setMethodCallHandler(null)
    }


    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        Log.d(TAG, "method call: ${call.method}")

        when (call.method) {
            "init" -> init(call, result)
            else -> result.notImplemented()
        }
    }

    private fun init(call: MethodCall, result: MethodChannel.Result) {
        val arguments: Map<String, Any> = call.arguments()

        Log.d(TAG, "init: $arguments")

        val customerID = arguments["customerId"] as String
        val sessionId = arguments["sessionId"] as? String ?: ""
        val domainSecret = arguments["domainSecret"] as? String ?: ""
        val mediaID = arguments["mediaId"] as String
        val autoplay = arguments["autoplay"] as? Boolean ?: false
        val revolverPlay = arguments["revolverPlay "] as? Boolean ?: false
        val adType = "VAST" //arguments["adType"] as? String ?: "no override"
        val playMode = "single" //arguments["playMode"] as? String ?: "video"
        val exitPlayMode = 0

        val np: NexxPlayer = nexxPlayer as NexxPlayer
        val npl: NexxPlayerNotification = nexxPlayer as NexxPlayerNotification
        npl.addEventListener(this)

        // auto play
        val autoPlayMode = if (autoplay) AutoPlayMode.StartImmediately else AutoPlayMode.ShowStartScreen
        np.overrideAutoPlay(autoPlayMode)

        // revolver play
        val autoPlayNextMode = if (revolverPlay) AutoPlayNextMode.EnableRevolverPlay else AutoPlayNextMode.DisableRevolverPlay
        np.overrideAutoPlayNext(autoPlayNextMode)
        // exit play mode

        // exit play mode
        val o_exitPlayMode: ExitPlayMode = Utils.getExitMode(exitPlayMode)
        np.overrideExitPlayMode(o_exitPlayMode)

        if (adType != "no override") {
            np.overrideAdType(adType.toLowerCase());
        }

        val skin = LoaderSkin.DEFAULT
        np.setLoaderSkin(skin)

//        np.setDataMode(DataMode.STATIC)
//        np.setSSL(true)

        np.startPlay(null, customerID, Utils.getPlayMode(playMode), mediaID, 0, 0);
    }

    override fun onDetachedFromActivity() {
        Log.d("State", "onDetachedFromActivity");
//        TODO("Not yet implemented")
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        TODO("Not yet implemented")
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        Log.d("State", "onAttachedToActivity");
        nexxPlayer.setWindow(binding.activity.window)

//        binding.activity.
    }

    override fun onDetachedFromActivityForConfigChanges() {
        TODO("Not yet implemented")
    }

    override fun onFullScreen(p0: Boolean) {
        TODO("Not yet implemented")
    }

    override fun onPlayerError(p0: String?, p1: String?) {
        Log.e(TAG, "on player error: $p0, $p1")
    }

    override fun onPlayerStateChanged(p0: Boolean, p1: Player.State?) {
        TODO("Not yet implemented")
        Log.d("State", "onPlayerStateChanged $p1");
    }

    override fun onVideoSizeChanged(p0: Int, p1: Int, p2: Float) {
        TODO("Not yet implemented")
    }

    override fun onPlayerEvent(playerEvent: PlayerEvent?, p1: Any?) {
        if (playerEvent == PlayerEvent.ADCLICKED) {
            Log.d("EVENTS in App", "AD CLICKED EVENT!");
        }

        if (playerEvent == PlayerEvent.ADSTARTED) {
            Log.d("EVENTS in App", "AD STARTED EVENT!");
        }

        if (playerEvent == PlayerEvent.ADENDED) {
            Log.d("EVENTS in App", "AD ENDED EVENT!");
        }

        if (playerEvent == PlayerEvent.ADERROR) {
            Log.e("EVENTS in App", "AD ERROR!");
        }

        if (playerEvent == PlayerEvent.ADRESUMED) {
            Log.d("EVENTS in App", "AD RESUMED!");
        }

        Log.d(TAG, "Player event in App: ${playerEvent.toString()}, $p1");
    }

}

`
I can attach my complete project if you want.

**Comment by vAStrohhecker** [comment]
i've attached my main class:
[NexxPlayer.zip](https://github.com/3qnexx/nexxPLAY-android/files/5050912/NexxPlayer.zip)

If you want i can attach my complete project.

Cheers

**Comment by vAStrohhecker** [comment]
Do you need more code from me? If so i can provide it, no problem.

**Comment by mfentross** [comment]
Hi @vAStrohhecker,

I tried to reproduce the issue, but was not successful with that. Could you please share a project? Afaik we already had clients who used our player in Flutter projects.

**Comment by vAStrohhecker** [comment]
Here is my complete Flutter Plugin Project:
[flutter_nexxtv.zip](https://github.com/3qnexx/nexxPLAY-android/files/5116507/flutter_nexxtv.zip)

If you have customers that already built Flutter apps with your SDK then i'm sure i am missing a critical piece which prevents me from getting this thing to work. Any pointers would be much appreciated.

Included in the project is an "example" folder containing a simple App using the Plugin.
Compiled APK can be downloaded here: https://oc.vonaffenfels.de/s/t6jf8oGDMDWXHkW

**Comment by vAStrohhecker** [comment]
Hi @mfentross , i have heard that the problem is Kotlin in conjunction with Flutter. I can rewrite the Plugin in Java, no problem. I will give this a shot today.

**Comment by vAStrohhecker** [comment]
@mfentross @neko-fire : Here is the new Java plugin project. Sadly, it didn't change anything. 
https://oc.vonaffenfels.de/s/9XmfwiRnZspZfbp

this is the compiled debug APK:
[flutter_nexxtv2.zip](https://github.com/3qnexx/nexxPLAY-android/files/5160858/flutter_nexxtv2.zip)

This is the log:

`D/NEXX-UI: setting onclick listener for surface
I/NEXX: got media data, 1 items
D/de.vonaffenfels.flutter_nexxtv2.NexxPlayer: Player event in App: METADATA, [tv.nexx.android.player.Media@859058b]
D/tv.nexx.android.player.logic.PlayerLogicStateMachine: startMediaOrGetReady()
D/de.vonaffenfels.flutter_nexxtv2.NexxPlayer: Player event in App: PLAYERREADY, null
I/NEXX: release
D/NEXX: playing media http://nq-p01.akamaized.net/c64f932b-3230-4874-a0cf-db1f7ef0e353/1520563_src.ism/Manifest(format=mpd-time-cmaf)
I/NEXX: prepare http://nq-p01.akamaized.net/c64f932b-3230-4874-a0cf-db1f7ef0e353/1520563_src.ism/Manifest(format=mpd-time-cmaf), start position 0
I/NEXX: prepare has no effect
D/NEXX: Sequencer event startMedia in state MediaState, transitioning to 2
D/showAgeRestriction: setting header: Achtung
D/showAgeRestriction: setting body: Dieses Video könnte jugendgefährdende Inhalte enthalten.
E/DecorView: mWindow.mActivityCurrentConfig is null
I/System.out: (HTTask: Wating for debug ...
I/NEXX: got exit play data, 10 items
D/NEXX: using video thumb
D/NEXX: using video thumb
D/NEXX: exit play media list available, size 10
`
Same message "prepare has no effect".

**Comment by mfentross** [comment]
Hi @vAStrohhecker,

I investigated a bit more: the issue seems to be related to the view anchor you are providing to the player. As of now, the player needs a FrameLayout as the root view. Could you please check if its possible to provide the player with such kind of layout via Flutter?

**Comment by vAStrohhecker** [comment]
@mfentross All right, i will give this a shot.

**Comment by vAStrohhecker** [comment]
@mfentross If you look in my code, the player gets a FrameLayout via setViewRoot. I create one on the fly. Is that not correct? I'm trying for hours now, but even a FrameLayout definded by XML doesn't fix the problem. Same thing, Ui is showing but video is not playing.

**Comment by vAStrohhecker** [comment]
@mfentross i have updated my sources so that it uses Layout XML Files, but no luck. Here is the source code:

[flutter_nexxtv2_layoutxml.zip](https://github.com/3qnexx/nexxPLAY-android/files/5208869/flutter_nexxtv2_layoutxml.zip)

Sorry for the inconvenience.
